Fix audience method for null application
Audience method returns an error if called when the application on the access token is null. I have changed it to return null instead
`NoMethodError: undefined method `uid' for nil:NilClass`
```
"/code/masterlock/doorkeeper-openid_connect/lib/doorkeeper/openid_connect/id_token.rb:49:in `audience'",
"/code/masterlock/doorkeeper-openid_connect/lib/doorkeeper/openid_connect/id_token.rb:19:in `claims'",
"/code/masterlock/doorkeeper-openid_connect/lib/doorkeeper/openid_connect/id_token.rb:28:in `as_json'",
"/code/masterlock/doorkeeper-openid_connect/lib/doorkeeper/openid_connect/id_token.rb:32:in `as_jws_token'",
"/code/masterlock/doorkeeper-openid_connect/lib/doorkeeper/openid_connect/oauth/token_response.rb:12:in `body'",
"/code/masterlock/doorkeeper/app/controllers/doorkeeper/tokens_controller.rb:7:in `create'"
```